<?php

namespace AdvertBundle\Repository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
    public function checkCity($id)
    {
//        $q = 'SELECT a FROM AdvertBundle\Entity\Advert a WHERE a.city_id = '.$id;
//
//         $query = $this->getEntityManager()->createQuery($q);
//         return $query->execute();
        return $aval = $this->createQueryBuilder('c')->select('c.id')
            ->where('c.cityId = :id')->setParameter(':id', $id)
            ->getQuery()->getScalarResult();


    }


    public function checkCategory($id)
    {
        return $aval = $this->createQueryBuilder('ca')->select('ca.id')
            ->where('ca.ctegoryId = :id')->setParameter(':id', $id)
            ->getQuery()->getScalarResult();

    }
}
